### ISSUE TITLE
Replace momentjs

### ISSUE THREAD

**Issue by oaksprout** [ceramic-tiles/web#19]
Moment is really heavy and I'm not sure we're doing anything with it which couldn't be done with the lighter weight `date-fns` or `dayjs`.

**Comment by emersonmacro** [comment]
Hi @oaksprout, I took a stab at this issue here https://github.com/ceramic-tiles/web/pull/20. I've been exploring Ceramic recently and Tiles seems like a really cool project. Cheers!

**Comment by oaksprout** [comment]
Hey @emersonmacro! I thought I'd replied but looks like I didn't. Thank you very much for this contribution! If you have Discord it would be great if you dropped your username so I/we can reach out – curious to hear more about your interest in Ceramic and what led you to Tiles.

**Comment by emersonmacro** [comment]
Hey @oaksprout, no worries! `emersonmacro` on Discord as well, would be happy to connect.

**Comment by oaksprout** [comment]
@emersonmacro awesome! Can you also drop the four digit #tag after your Discord name? Can't seem to find you otherwise.

**Comment by emersonmacro** [comment]
My bad - I'm still a relative noob with Discord. `emersonmacro#9446`
